LOCAL_PATH := $(call my-dir)
#TARGET_INITRD_SCRIPTS := $(LOCAL_PATH)/m1400_info
#TARGET_PREBUILT_APPS := $(subst $(LOCAL_PATH)/,,$(wildcard $(LOCAL_PATH)/app/*))
TARGET_KERNEL_CONFIG := $(LOCAL_PATH)/m1400_defconfig
LOCAL_FIRMWARES := ipw2200-bss.fw

include $(GENERIC_X86_ANDROID_MK)
